# Generated by Django 5.0 on 2023-12-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicdesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designame', models.CharField(max_length=260)),
                ('desigcode', models.CharField(max_length=260)),
                ('desigstatus', models.IntegerField(default=1)),
            ],
        ),
    ]
