# Generated by Django 5.0 on 2023-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0002_academicdesignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicqualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationname', models.CharField(max_length=260)),
                ('qualificationstatus', models.IntegerField(default=1)),
            ],
        ),
    ]
