# Generated by Django 5.0 on 2023-12-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0003_academicqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=260)),
                ('classstatus', models.IntegerField(default=1)),
            ],
        ),
    ]
