# Generated by Django 5.0 on 2023-12-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0004_academicclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisionname', models.CharField(max_length=260)),
                ('divisionstatus', models.IntegerField(default=1)),
            ],
        ),
    ]
