# Generated by Django 5.0 on 2024-01-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0005_academicdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_cat_name', models.CharField(max_length=260)),
                ('employee_cat_area', models.IntegerField(choices=[(1, 'Accountant'), (2, 'Teacher'), (3, 'Mess'), (4, 'Librarian'), (5, 'other')])),
                ('employee_cat_status', models.IntegerField(default=1)),
            ],
        ),
    ]
